using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Feather.GraphQL.Linq.Analyzers.Tests;

/// <summary>
/// The structs a reply is modelled as, and the reader written over them.
/// </summary>
/// <remarks>
/// These assert on generated source, which is usually a brittle thing to do. It is worth it here
/// because the source <em>is</em> the product: what this emits has to compile in someone else's
/// assembly, read their reply correctly, and be legible enough that a person can check the second
/// claim by reading it. A test that only asserted the model would not notice if the code were
/// unreadable, and one that only ran the code would not notice if it stopped being reviewable.
/// </remarks>
[TestFixture]
public class ResponseStructTests
{
    /// <summary>The selection a chain naming the whole element produces.</summary>
    [Test]
    public void A_flat_selection_becomes_one_struct()
    {
        string source = Emit("c => new { c.Name, c.Code }");

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("file readonly struct CountriesByCode_Row"));
            Assert.That(source, Does.Contain("public readonly string Name;"));
            Assert.That(source, Does.Contain("public readonly string Code;"));
            Assert.That(source, Does.Contain("reader.ValueTextEquals(\"name\"u8)"));

            // Nothing of this library's: the reader is Utf8JsonReader and the BCL.
            Assert.That(source, Does.Contain("reader.GetString()"));
            Assert.That(source, Does.Not.Contain("Feather.GraphQL.Serialization"));
        });
    }

    /// <summary>
    /// A nested object becomes a struct of its own, named for the member that holds it.
    /// </summary>
    [Test]
    public void A_nested_object_becomes_its_own_struct()
    {
        string source = Emit("c => new { c.Name, c.Continent }");

        Assert.Multiple(() =>
        {
            // Its own reader, but the declared type rather than a mirror of it: what a nested
            // object needs is to be read field by field, not to be a different type while it is.
            Assert.That(source, Does.Contain("CountriesByCode_ContinentReader"));

            Assert.That(
                source,
                Does.Contain("public readonly global::Feather.GraphQL.Linq.Analyzers.Tests.Continent Continent;"));

            // The nested struct is written first, so the one that holds it can name it.
            Assert.That(
                source.IndexOf("struct CountriesByCode_Continent", StringComparison.Ordinal),
                Is.LessThan(source.IndexOf("struct CountriesByCode_Row", StringComparison.Ordinal)));
        });
    }

    /// <summary>A field the query never asked for has no member at all.</summary>
    /// <remarks>
    /// The whole point of modelling the reply rather than the type: <c>Country</c> has a code and
    /// a continent, and a query that asked for neither carries neither.
    /// </remarks>
    [Test]
    public void A_field_the_query_did_not_ask_for_is_not_a_member()
    {
        string source = Emit("c => new { c.Name }");

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("public readonly string Name;"));
            Assert.That(source, Does.Not.Contain("Code;"));
            Assert.That(source, Does.Not.Contain("Continent;"));
        });
    }

    /// <summary>
    /// The emitted source compiles, which is the claim every other assertion here rests on.
    /// </summary>
    /// <remarks>
    /// A generator that emits something plausible but uncompilable fails in the consumer's build
    /// with an error pointing at generated code they did not write. Compiling it here is the only
    /// way to find that out on this side of the seam.
    /// </remarks>
    [TestCase("c => new { c.Name, c.Code }", "Country", false)]
    [TestCase("c => new { c.Name, c.Continent }", "Country", false)]
    [TestCase("c => new { c.Name, c.Population, c.Area, c.Coastal }", "Region", false)]
    [TestCase("c => new { c.Name, c.Countries }", "Region", false)]
    [TestCase("c => new { c.Name, c.Code }", "Country", true)]
    [TestCase("c => new { c.Name, c.Continent }", "Country", true)]
    [TestCase("c => new { c.Name, c.Countries }", "Region", true)]
    [TestCase("c => new { c.Name, c.Founded, c.Money, c.Climate }", "Region", false)]
    [TestCase("c => new { c.Name, c.Founded, c.Money, c.Climate }", "Region", true)]
    [TestCase("c => new { c.Founded2, c.Id }", "Region", true)]
    [TestCase("c => new { c.Name, c.Tags }", "Region", true)]
    public void The_emitted_source_compiles(string projection, string element, bool direct)
    {
        string emitted = Emit(projection, element, direct);

        string file = "// <auto-generated/>\n#nullable enable\n\nnamespace Generated\n{\n"
            + emitted + "}\n";

        var compilation = CSharpCompilation.Create(
            "Emitted",
            [CSharpSyntaxTree.ParseText(file, new CSharpParseOptions(LanguageVersion.Preview))],
            SnippetReferences.All(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var errors = compilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.That(errors, Is.Empty,
            $"the emitted source did not compile: {string.Join("; ", errors.Select(e => e.ToString()))}"
            + "\n\n" + file);
    }

    /// <summary>Shows the emitted source, so it can be read rather than only asserted on.</summary>
    [Test]
    public void The_emitted_source_reads_as_code_a_person_could_have_written()
    {
        TestContext.Out.WriteLine(Emit("c => new { c.Name, c.Continent }"));

        Assert.Pass();
    }

    /// <summary>
    /// A list of objects becomes an array of the struct its elements are.
    /// </summary>
    /// <remarks>
    /// The shape that separates modelling a reply from modelling one row: a field can carry many
    /// of something, and the reader has to walk the array rather than the object.
    /// </remarks>
    [Test]
    public void A_list_of_objects_becomes_an_array_of_its_struct()
    {
        string source = Emit("c => new { c.Name, c.Countries }", "Region");

        Assert.Multiple(() =>
        {
            // The elements are the declared type, not a mirror of it — see
            // With_a_projection_the_mirror_keeps_the_queried_types_names for why.
            Assert.That(
                source,
                Does.Contain("public readonly global::Feather.GraphQL.Linq.Analyzers.Tests.Country[] Countries;"));

            Assert.That(source, Does.Contain("JsonTokenType.EndArray"));
        });
    }

    /// <summary>Numbers and their nullables read as themselves, not as strings.</summary>
    [Test]
    public void Numbers_read_through_their_own_getters()
    {
        string source = Emit("c => new { c.Population, c.Area, c.Coastal }", "Region");

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("reader.GetInt32()"));
            Assert.That(source, Does.Contain("reader.GetDouble()"));
            Assert.That(source, Does.Contain("reader.GetBoolean()"));

            // A number's getter throws on a null, so the token is checked before it is called.
            Assert.That(
                source,
                Does.Contain("reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? default : reader.GetInt32()"));
        });
    }

    /// <summary>Builds the model for one projection and writes it out.</summary>
    private static string Emit(string projection, string element = "Country", bool direct = false)
    {
        string source = $$"""
            using System.Linq;
            using Feather.GraphQL.Linq.Analyzers.Tests;

            public static class Snippet
            {
                public static object Run(System.Collections.Generic.IEnumerable<{{element}}> source)
                    => source.Select({{projection}});
            }
            """;

        var tree = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview));

        var compilation = CSharpCompilation.Create(
            "Response",
            [tree],
            SnippetReferences.All(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var errors = compilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.That(errors, Is.Empty,
            $"the snippet did not compile: {string.Join("; ", errors.Select(e => e.ToString()))}");

        var model = compilation.GetSemanticModel(tree);

        var lambda = tree.GetRoot().DescendantNodes().OfType<LambdaExpressionSyntax>().Single();
        var type = compilation.GetTypeByMetadataName(
            "Feather.GraphQL.Linq.Analyzers.Tests." + element)!;

        var selection = SelectionSetWriter.Build(type, lambda, model, default);
        Assert.That(selection, Is.Not.Null, "the selection set could not be built");

        var described = ResponseStructWriter.Describe("CountriesByCode", type, selection!, direct);
        Assert.That(described, Is.Not.Null, "the reply could not be modelled");

        var builder = new System.Text.StringBuilder();
        ResponseStructWriter.Write(builder, described!, "CountriesByCode");

        return builder.ToString();
    }

    // ---- how many of something reaches the member that asked for it -------------------------

    /// <summary>
    /// A member declared as a list is the list the reader accumulated.
    /// </summary>
    /// <remarks>
    /// Reading fills a list because that is the only shape that can be filled without knowing the
    /// count first. Where the member is declared as one, the two are the same object and there is
    /// no conversion at all — which is the reason to accumulate into a list rather than anything
    /// else.
    /// </remarks>
    [Test]
    public void A_list_member_is_the_list_that_was_read()
    {
        string source = Emit("r => new { r.Sites }", "Region", direct: true);

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("_sitesItems = new global::System.Collections.Generic.List<"));
            Assert.That(source, Does.Contain("_sites = _sitesItems;"));
            Assert.That(source, Does.Not.Contain("_sites = _sitesItems.ToArray()"));
        });
    }

    /// <summary>An array member still gets an array, which is a copy of the list.</summary>
    [Test]
    public void An_array_member_is_copied_out_of_the_list()
    {
        string source = Emit("r => new { r.Tags }", "Region", direct: true);

        Assert.That(source, Does.Contain("_tags = _tagsItems.ToArray();"));
    }

    /// <summary>
    /// A type that says how a collection expression builds one gets a collection expression.
    /// </summary>
    /// <remarks>
    /// <c>ImmutableArray</c> carries a <c>[CollectionBuilder]</c>, which is the type answering the
    /// only question that matters here — how one of it is made — in the form C# already knows how
    /// to ask.
    /// </remarks>
    [Test]
    public void A_type_a_collection_expression_builds_gets_one()
    {
        string source = Emit("r => new { r.Borders }", "Region", direct: true);

        Assert.That(source, Does.Contain("_borders = [.. _bordersItems];"));
    }

    /// <summary>A type with a constructor taking a collection is handed the list.</summary>
    [Test]
    public void A_type_with_a_constructor_taking_a_collection_is_handed_the_list()
    {
        string source = Emit("r => new { r.Ledger }", "Region", direct: true);

        Assert.That(source, Does.Contain(
            "_ledger = new global::Feather.GraphQL.Linq.Analyzers.Tests.Ledger(_ledgerItems);"));
    }

    /// <summary>
    /// A row of this file's own holds a read-only list where the member it mirrors is declared as
    /// something one already is.
    /// </summary>
    [Test]
    public void A_mirrored_read_only_member_is_held_read_only()
    {
        string source = Emit("r => new { r.Neighbours }", "Region", direct: false);

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain(
                "public readonly global::System.Collections.Generic.IReadOnlyList<"));

            Assert.That(source, Does.Contain("_neighbours = _neighboursItems;"));
        });
    }

    // ---- converters the model declared ------------------------------------------------------

    /// <summary>
    /// A member with its own converter is read through it, not through a getter.
    /// </summary>
    /// <remarks>
    /// The root of why anything used to fall back: a model that declares how a member is written
    /// and read has said what reading it means, and a second reader that decided otherwise would
    /// be reading something else. Copying the instruction over is the only way the two agree.
    /// </remarks>
    [Test]
    public void A_member_with_a_converter_is_read_through_it()
    {
        string source = Emit("c => new { c.Name, c.Founded }", "Region");

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("JsonConverter<global::System.DateTime> _foundedConverter"));
            Assert.That(source, Does.Contain("new global::Feather.GraphQL.Linq.Analyzers.Tests.EpochConverter()"));
            Assert.That(source, Does.Contain("_foundedConverter.Read(ref reader, typeof(global::System.DateTime)"));

            // And not through the getter it would otherwise have had.
            Assert.That(source, Does.Not.Contain("reader.GetDateTime()"));
        });
    }

    /// <summary>A converter declared on the type reaches every member of that type.</summary>
    [Test]
    public void A_converter_on_the_type_is_found_too()
    {
        string source = Emit("c => new { c.Name, c.Money }", "Region");

        Assert.That(source, Does.Contain("_moneyConverter.Read(ref reader"));
    }

    /// <summary>
    /// A factory is asked for its converter once, not once per row.
    /// </summary>
    /// <remarks>
    /// <c>JsonStringEnumConverter</c> is one, which is how an enum comes to be readable at all —
    /// and making one per row would cost more than the reading does.
    /// </remarks>
    [Test]
    public void A_converter_factory_is_asked_once()
    {
        string source = Emit("c => new { c.Name, c.Climate }", "Region");

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("static readonly"));
            Assert.That(source, Does.Contain("CreateConverter("));
            Assert.That(source, Does.Contain("JsonStringEnumConverter"));
        });
    }

    /// <summary>Dates and identifiers read through the getters that parse what the writer wrote.</summary>
    [Test]
    public void Well_known_scalars_read_through_their_own_getters()
    {
        string source = Emit("c => new { c.Founded2, c.Id }", "Region");

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("reader.GetDateTime()"));
            Assert.That(source, Does.Contain("reader.GetGuid()"));
        });
    }

    // ---- reading straight into the caller's type --------------------------------------------

    /// <summary>
    /// With no projection, the rows are the queried type and are built as they are read.
    /// </summary>
    /// <remarks>
    /// The optimisation the chain's shape decides: a mirror struct would exist only to be copied
    /// out of, so when nothing is going to reshape the rows there is no mirror and no copy.
    /// </remarks>
    [Test]
    public void With_no_projection_the_reader_builds_the_queried_type()
    {
        string source = Emit("c => new { c.Name, c.Code }", direct: true);

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("global::Feather.GraphQL.Linq.Analyzers.Tests.Country Read("));
            Assert.That(source, Does.Contain("Name = _name"));
            Assert.That(source, Does.Contain("Code = _code"));

            // No mirror of the payload is declared at all.
            Assert.That(source, Does.Not.Contain("struct CountriesByCode_Row"));
        });
    }

    /// <summary>The nested type is built the same way, not mirrored either.</summary>
    [Test]
    public void With_no_projection_a_nested_object_is_built_too()
    {
        string source = Emit("c => new { c.Name, c.Continent }", direct: true);

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("global::Feather.GraphQL.Linq.Analyzers.Tests.Continent Read("));
            Assert.That(source, Does.Not.Contain("struct CountriesByCode_Continent"));
        });
    }

    /// <summary>
    /// With a projection, the row is mirrored — and the mirror's members carry the queried type's
    /// own names, so the projection compiles against it unchanged.
    /// </summary>
    /// <remarks>
    /// <para>
    /// That is what makes the remapping free to generate: <c>c => new Row { Title = c.Name }</c>
    /// needs no rewriting to run over <c>CountriesByCode_Row</c>, because <c>c.Name</c> means the
    /// same thing on both.
    /// </para>
    /// <para>
    /// A member that is itself an object is the declared type rather than a mirror of it. The
    /// mirror exists so a row carries exactly the selected fields; a member needs no such thing,
    /// and building it as declared is what lets a projection pass the whole object along —
    /// <c>new Summary(c.Name, c.Continent)</c> — instead of only its scalars.
    /// </para>
    /// </remarks>
    [Test]
    public void With_a_projection_the_mirror_keeps_the_queried_types_names()
    {
        string source = Emit("c => new { c.Name, c.Continent }");

        Assert.Multiple(() =>
        {
            Assert.That(source, Does.Contain("struct CountriesByCode_Row"));
            Assert.That(source, Does.Contain("public readonly string Name;"));

            Assert.That(
                source,
                Does.Contain("public readonly global::Feather.GraphQL.Linq.Analyzers.Tests.Continent Continent;"));
        });
    }
}

/// <summary>
/// A type carrying the shapes a reply model has to handle beyond flat strings.
/// </summary>
/// <remarks>
/// Declared here rather than added to the corpus model, which every document test compares
/// against byte for byte: a field added there would change documents those tests pin.
/// </remarks>
public class Region
{
    public string Name { get; set; } = "";

    public int Population { get; set; }

    public double? Area { get; set; }

    public bool Coastal { get; set; }

    public Country[] Countries { get; set; } = [];

    /// <summary>A list of scalars, which is a leaf on the wire but still an array.</summary>
    public string[] Tags { get; set; } = [];

    /// <summary>Many of something, held the way most models hold many of something.</summary>
    public System.Collections.Generic.List<Country> Sites { get; set; } = [];

    /// <summary>Many of something the caller says nothing may be added to.</summary>
    public System.Collections.Generic.IReadOnlyCollection<Country> Neighbours { get; set; } = [];

    /// <summary>Many of something only a collection expression builds.</summary>
    public System.Collections.Immutable.ImmutableArray<Country> Borders { get; set; }

    /// <summary>Many of something with a constructor that takes them.</summary>
    public Ledger Ledger { get; set; } = new([]);

    /// <summary>A member whose model says how it is written, and so how it is read.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(EpochConverter))]
    public DateTime Founded { get; set; }

    /// <summary>The same date with nothing said about it: the serializer's own format.</summary>
    public DateTime Founded2 { get; set; }

    public Guid Id { get; set; }

    /// <summary>A type that carries its own converter, rather than a member that does.</summary>
    public Money Money { get; set; }

    /// <summary>An enum by name, which takes a factory to read.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public Climate Climate { get; set; }
}

/// <summary>
/// A collection of the caller's own, built the way most of them are: by handing it the values.
/// </summary>
public sealed class Ledger(System.Collections.Generic.IEnumerable<string> entries)
    : System.Collections.Generic.IEnumerable<string>
{
    private readonly System.Collections.Generic.List<string> _entries = [.. entries];

    public System.Collections.Generic.IEnumerator<string> GetEnumerator() => _entries.GetEnumerator();

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
}

/// <summary>Whatever this means on the wire, the model is the one that says so.</summary>
[System.Text.Json.Serialization.JsonConverter(typeof(MoneyConverter))]
public readonly record struct Money(decimal Amount);

public enum Climate { Temperate, Tropical, Arid }

/// <summary>A converter of the model's own, which a generated reader has to read through.</summary>
public sealed class EpochConverter : System.Text.Json.Serialization.JsonConverter<DateTime>
{
    public override DateTime Read(
        ref System.Text.Json.Utf8JsonReader reader,
        Type typeToConvert,
        System.Text.Json.JsonSerializerOptions options)
        => DateTime.UnixEpoch.AddSeconds(reader.GetInt64());

    public override void Write(
        System.Text.Json.Utf8JsonWriter writer,
        DateTime value,
        System.Text.Json.JsonSerializerOptions options)
        => writer.WriteNumberValue((long)(value - DateTime.UnixEpoch).TotalSeconds);
}

/// <inheritdoc cref="EpochConverter"/>
public sealed class MoneyConverter : System.Text.Json.Serialization.JsonConverter<Money>
{
    public override Money Read(
        ref System.Text.Json.Utf8JsonReader reader,
        Type typeToConvert,
        System.Text.Json.JsonSerializerOptions options)
        => new(reader.GetDecimal());

    public override void Write(
        System.Text.Json.Utf8JsonWriter writer,
        Money value,
        System.Text.Json.JsonSerializerOptions options)
        => writer.WriteNumberValue(value.Amount);
}
