using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Feather.GraphQL.Linq.Analyzers;

/// <summary>
/// Registers the consumer's <c>JsonSerializerContext</c>s before anything reads a reply.
/// </summary>
/// <remarks>
/// <para>
/// A compiled query reads its reply through a generated reader and needs none of this. What does
/// need it is the string path — a document sent by hand and read into a declared type — which goes
/// through <c>System.Text.Json</c> and has to be told which contract describes the type, or fall
/// back to reflection that an AOT build cannot support.
/// </para>
/// <para>
/// Contexts are declared in the consumer's own source, because <c>System.Text.Json</c>'s generator
/// cannot see what another generator emits. Finding them is all this does — it used to be one
/// half of a generator that also built field tables for the runtime translator, and that half went
/// with the translator.
/// </para>
/// </remarks>
[Generator]
public sealed class JsonContextGenerator : IIncrementalGenerator
{
    private const string Context = "System.Text.Json.Serialization.JsonSerializerContext";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contexts = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, token) => Named(ctx, token))
            .Where(static name => name is not null)
            .Collect();

        context.RegisterSourceOutput(contexts, static (source, found) => Emit(source, found!));
    }

    /// <summary>The fully qualified name of a context declared here, if this is one.</summary>
    private static string? Named(GeneratorSyntaxContext context, CancellationToken token)
    {
        if (context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node, token)
            is not INamedTypeSymbol { IsAbstract: false } type)
            return null;

        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == Context)
                return type.ToDisplayString(_qualified);
        }

        return null;
    }

    /// <summary>
    /// Writes the module initializer that registers them.
    /// </summary>
    /// <remarks>
    /// Sorted, so two builds of the same source emit the same file — a generator whose output
    /// depends on the order the compiler happened to walk syntax makes its consumers rebuild for
    /// no reason.
    /// </remarks>
    private static void Emit(SourceProductionContext context, ImmutableArray<string?> found)
    {
        var names = new SortedSet<string>(StringComparer.Ordinal);

        foreach (string? name in found)
        {
            if (name is not null)
                names.Add(name);
        }

        if (names.Count == 0)
            return;

        var source = new StringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("namespace Feather.GraphQL.Linq.Generated")
            .AppendLine("{")
            .AppendLine("    /// <summary>Registers this assembly's JSON contexts before a reply is read.</summary>")
            .AppendLine("    internal static class GraphQLGeneratedJsonContexts")
            .AppendLine("    {")
            .AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]")
            .AppendLine("        internal static void Register()")
            .AppendLine("        {");

        foreach (string name in names)
        {
            source.Append("            global::Feather.GraphQL.Metadata.GraphQLJsonContextRegistry.Register(")
                .Append(name).AppendLine(".Default);");
        }

        source.AppendLine("        }")
            .AppendLine("    }")
            .AppendLine("}");

        context.AddSource("GraphQLGeneratedJsonContexts.g.cs", source.ToString());
    }

    private static readonly SymbolDisplayFormat _qualified =
        SymbolDisplayFormat.FullyQualifiedFormat;
}
